# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               theminerleague
tagline:             'data "science"'
description:         personal blog
url:                 http://chrisaddy.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Chris Addy
  url:               https://twitter.com/
  email:             chris.william.addy@gmail.com
